### ISSUE TITLE
[bug]: libunwind.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by makorne** [FedericoBruzzone/tgt#32]
### Describe the bug

Package libunwind-1.6.2-5.fc37.x86_64 is already installed.

### Reproduction steps

1. cargo install tgt 
2. git clone this repo...   cargo build --features download-tdlib

### Expected behavior

Hi!
Thank you for your great crate!

Install and build  

### Logs and screenshots

1) cargo install tgt
```
Compiling tgt v0.1.10
error: failed to run custom build command for `tgt v0.1.10`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installDYwN1V/release/build/tgt-2b69a44ae29c83f5/build-script-build` (exit status: 127)
  --- stderr
  /tmp/cargo-installDYwN1V/release/build/tgt-2b69a44ae29c83f5/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
```
2) cargo build --features download-tdlib
```
...
  Compiling tdlib-rs v1.0.4
   Compiling tgt v0.1.10
error: failed to run custom build command for `tgt v0.1.10`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installDYwN1V/release/build/tgt-2b69a44ae29c83f5/build-script-build` (exit status: 127)
  --- stderr
  /tmp/cargo-installDYwN1V/release/build/tgt-2b69a44ae29c83f5/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
```

### Method of Installation

Cargo

### tgt version

0.1.10

### Operating System (including version and architecture)

Fedora 37

### rustc and rustup target (including versions)

rustc version is `rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by FedericoBruzzone** [comment]
Thank you for your instant feedback! 

We are working on the next stable release that it will be the next week; remember to reinstall as soon as it comes out :D

Can you show me the output of these two commands:
```bash
ls -lha /usr/lib64/libunwind*
```
```bash
ls -lha /usr/lib/libunwind*
```

**Comment by makorne** [comment]
ls -lha /usr/lib64/libunwind*
```
lrwxrwxrwx 1 root root  27 Nov 17  2022 /usr/lib64/libunwind-coredump.so -> libunwind-coredump.so.0.0.0
lrwxrwxrwx 1 root root  27 Nov 17  2022 /usr/lib64/libunwind-coredump.so.0 -> libunwind-coredump.so.0.0.0
-rwxr-xr-x 1 root root 20K Nov 17  2022 /usr/lib64/libunwind-coredump.so.0.0.0
lrwxrwxrwx 1 root root  19 Nov 17  2022 /usr/lib64/libunwind-generic.so -> libunwind-x86_64.so
-rw-r--r-- 1 root root 91K Nov 17  2022 /usr/lib64/libunwind-ptrace.a
lrwxrwxrwx 1 root root  18 Nov 17  2022 /usr/lib64/libunwind.so -> libunwind.so.8.0.1
lrwxrwxrwx 1 root root  18 Nov 17  2022 /usr/lib64/libunwind.so.8 -> libunwind.so.8.0.1
-rwxr-xr-x 1 root root 57K Nov 17  2022 /usr/lib64/libunwind.so.8.0.1
lrwxrwxrwx 1 root root  25 Nov 17  2022 /usr/lib64/libunwind-x86_64.so -> libunwind-x86_64.so.8.0.1
lrwxrwxrwx 1 root root  25 Nov 17  2022 /usr/lib64/libunwind-x86_64.so.8 -> libunwind-x86_64.so.8.0.1
-rwxr-xr-x 1 root root 69K Nov 17  2022 /usr/lib64/libunwind-x86_64.so.8.0.1

```
ls -lha /usr/lib/libunwind*
ls: cannot access '/usr/lib/libunwind*': No such file or directory

**Comment by FedericoBruzzone** [comment]
Thank you @makorn !

I'm pretty sure it's enough to run these two commands:
```bash
ln -s /usr/lib64/libunwind.so.8.0.1 /usr/lib64/libunwind.so.1
```
```bash
ln -s /usr/lib64/libunwind-x86_64.so.8.0.1 /usr/lib64/libunwind-x86_64.so.1
```

Please let us know if it works!

**Comment by makorne** [comment]
Gold medal! It's work!

**Comment by FedericoBruzzone** [comment]
It was a pleasure to help you! :D

**Comment by mohammadazeemwani** [comment]
╰─➤  ln -s /usr/lib64/libunwind.so.8.0.1 /usr/lib64/libunwind.so.1      101 ↵
`ln: /usr/lib64/libunwind.so.1: No such file or directory`


╰─➤  ln -s /usr/lib64/libunwind-x86_64.so.8.0.1 /usr/lib64/libunwind-x86_64.so.1
`ln: /usr/lib64/libunwind-x86_64.so.1: No such file or directory`


=== I am on macos, what should I do ?
=== macOS Tahoe 26.2 arm64

My error: 
```
╰─➤  CARGO_TARGET_DIR=/var/folders/s0/v1sz49ld6yb5l2q90_vyzlpw0000gn/T/cargo-install6NVhar RUST_BACKTRACE=1 cargo install tgt
    Updating crates.io index
  Installing tgt v1.0.0
    Updating crates.io index
     Locking 491 packages to latest compatible versions
      Adding config v0.14.1 (available: v0.15.19)
      Adding crossterm v0.28.1 (available: v0.29.0)
      Adding dirs v5.0.1 (available: v6.0.0)
      Adding generic-array v0.14.7 (available: v0.14.9)
      Adding ratatui v0.27.0 (available: v0.30.0)
      Adding ratatui-image v1.0.5 (available: v10.0.5)
      Adding reqwest v0.12.28 (available: v0.13.2)
      Adding signal-hook v0.3.18 (available: v0.4.3)
      Adding zip v2.4.2 (available: v7.4.0)
   Compiling tdlib-rs v1.2.0
error: failed to run custom build command for `tdlib-rs v1.2.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/var/folders/s0/v1sz49ld6yb5l2q90_vyzlpw0000gn/T/cargo-install6NVhar/release/build/tdlib-rs-e6ded99363b6de1d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr

  thread 'main' panicked at /Users/mohammadazeemwani/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tdlib-rs-1.2.0/build.rs:174:40:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
  stack backtrace:
     0: __rustc::rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: build_script_build::download_tdlib
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by FedericoBruzzone** [comment]
> ╰─➤  ln -s /usr/lib64/libunwind.so.8.0.1 /usr/lib64/libunwind.so.1      101 ↵
> `ln: /usr/lib64/libunwind.so.1: No such file or directory`
> 
> 
> ╰─➤  ln -s /usr/lib64/libunwind-x86_64.so.8.0.1 /usr/lib64/libunwind-x86_64.so.1
> `ln: /usr/lib64/libunwind-x86_64.so.1: No such file or directory`
> 
> 
> === I am on macos, what should I do ?
> === macOS Tahoe 26.2 arm64
> 
> My error: 
> ```
> ╰─➤  CARGO_TARGET_DIR=/var/folders/s0/v1sz49ld6yb5l2q90_vyzlpw0000gn/T/cargo-install6NVhar RUST_BACKTRACE=1 cargo install tgt
>     Updating crates.io index
>   Installing tgt v1.0.0
>     Updating crates.io index
>      Locking 491 packages to latest compatible versions
>       Adding config v0.14.1 (available: v0.15.19)
>       Adding crossterm v0.28.1 (available: v0.29.0)
>       Adding dirs v5.0.1 (available: v6.0.0)
>       Adding generic-array v0.14.7 (available: v0.14.9)
>       Adding ratatui v0.27.0 (available: v0.30.0)
>       Adding ratatui-image v1.0.5 (available: v10.0.5)
>       Adding reqwest v0.12.28 (available: v0.13.2)
>       Adding signal-hook v0.3.18 (available: v0.4.3)
>       Adding zip v2.4.2 (available: v7.4.0)
>    Compiling tdlib-rs v1.2.0
> error: failed to run custom build command for `tdlib-rs v1.2.0`
> note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
> 
> Caused by:
>   process didn't exit successfully: `/var/folders/s0/v1sz49ld6yb5l2q90_vyzlpw0000gn/T/cargo-install6NVhar/release/build/tdlib-rs-e6ded99363b6de1d/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=build.rs
> 
>   --- stderr
> 
>   thread 'main' panicked at /Users/mohammadazeemwani/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tdlib-rs-1.2.0/build.rs:174:40:
>   called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: TimedOut }
>   stack backtrace:
>      0: __rustc::rust_begin_unwind
>      1: core::panicking::panic_fmt
>      2: core::result::unwrap_failed
>      3: build_script_build::download_tdlib
>      4: build_script_build::main
>      5: core::ops::function::FnOnce::call_once
>   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

You solved it, didn't you?

**Comment by mohammadazeemwani** [comment]
Yes; how ??
How do you know man ? 
You really know the heartbeat of this project.

**Comment by FedericoBruzzone** [comment]
Due to other issues you commented :'D

**Comment by mohammadazeemwani** [comment]
xD xP
