### ISSUE TITLE
[bug]: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by AndrielFR** [FedericoBruzzone/tgt#39]
### Describe the bug

failed to build the tgt

### Reproduction steps

1. `git clone git@github.com:FedericoBruzzone/tgt.git`
2. `cd tgt`
3. `cargo build --release --features download-tdlib`
#

### Expected behavior

Install and work.

### Logs and screenshots

```
Compiling tgt v1.0.0 (/home/celly/tgt)
error: failed to run custom build command for `tgt v1.0.0 (/home/celly/tgt)`

Caused by:
  process didn't exit successfully: `/home/celly/tgt/target/release/build/tgt-fb0c1f67b870d63c/build-script-build` (exit status: 127)
  --- stderr
  /home/celly/tgt/target/release/build/tgt-fb0c1f67b870d63c/build-script-build: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

### Method of Installation

Build from source

### tgt version

git latest

### Operating System (including version and architecture)

Arch Linux x86_64, 6.10.3-arch1-2

### Terminal and Command Line Interface (CLI) (including versions)

fish, version 3.7.1

### rustc and rustup target (including versions)

rustc 1.80.0 (051478957 2024-07-21)

**Comment by AndrielFR** [comment]
I installed `libc++` and `libc++abi` from extra arch's repository and worked, later i checked https://github.com/FedericoBruzzone/tgt/issues/32 and fixed the remaining error.

**Comment by FedericoBruzzone** [comment]
Perfect, thank you for reporting it! 🫶
