### ISSUE TITLE
How do I send a message?

### ISSUE THREAD

**Issue by im-izz** [FedericoBruzzone/tgt#65]
### Describe the bug

How can I send message when I'm focused on the prompt?

### Reproduction steps

ctrl+3 / ctrl+down
(default is alt and I changed it to ctrl)

### Expected behavior

Send message

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

Windows 10

### Terminal and Command Line Interface (CLI) (including versions)

wezterm nightly

**Comment by im-izz** [comment]
Oh, how can I change it to ctrl+enter? alt enter is used by glazewm for opening the terminal and the whole alt key is used to switch my workspaces thats why I use ctrl

**Comment by FedericoBruzzone** [comment]
Right now the only hardcodrd keymaps are the prompt one, we should work on this feature.
I suggest you change the terminal one for the moment, could you work on it?

**Comment by im-izz** [comment]
I see, It's fine I can use it when it updates and since I have school I can't work on that unfortunately. maybe in future tho!
