### ISSUE TITLE
[feature]: Vim-like keybindings!

### ISSUE THREAD

**Issue by elogikalaf** [FedericoBruzzone/tgt#67]
The Current Keybindings seem a bit intuitive and hard to use, using a standard way to control the panes seems like a better option if possible, or at least giving the options to switch key bindings. 

using vim-like key bindings, which is used in projects like spotify-tui or this [spicetify](https://spicetify.app/docs/advanced-usage/extensions#keyboard-shortcut) extension. such as using escape to go out of a chat/chat list and using vim key motions (J K L H) to switch to other panes, and then hitting enter to focus on the the desired pane.

I don't know how approachable and doable this is but I think a better key biding scheme can improve the user experience, specially considering alt+enter or alt+right is binded to other things in my terminal right now.
thanks!

**Comment by Andreal2000** [comment]
The app currently support custom keybindings, you can read more info [here](https://github.com/FedericoBruzzone/tgt/blob/main/docs/configuration/keymap.toml.md).
There is even an already pre made vim keymap [here](https://github.com/FedericoBruzzone/tgt/blob/main/docs/vim_keymap.toml), you can customize it to your preferences.

**Comment by elogikalaf** [comment]
oh thank you sorry I missed it!

**Comment by Andreal2000** [comment]
No problem, if this solve your issue tell me and i will close it or feel free to do it you.
