### ISSUE TITLE
[bug]: Installation error:linking with 'cc' failed:exit status 1

### ISSUE THREAD

**Issue by lasashq** [FedericoBruzzone/tgt#71]
### Describe the bug

couldn't install

### Reproduction steps

1. cargo install tgt
2.wait

### Expected behavior

I wanted it to be installed

### Logs and screenshots

```
   Compiling tgt v1.0.0
error: linking with `cc` failed: exit status: 1
```

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

Arch Linux, kernel version: 6.11.2-arch1-1

### Terminal and Command Line Interface (CLI) (including versions)

kitty, zsh

### rustc and rustup target (including versions)

latest ones

**Comment by FedericoBruzzone** [comment]
Hi,
Thanks for opening an issue.

You can try to install base-devel on Arch (`sudo pacman -S base-devel`) and reinstall tgt.
Please, let us know if it works :D

**Comment by lasashq** [comment]
> Hi, Thanks for opening an issue.
> 
> You can try to install base-devel on Arch (`sudo pacman -S base-devel`) and reinstall tgt. Please, let us know if it works :D

It is installed on my PC. I reinstalled it again, and cargo install tgt fails to compile again with the same problem

**Comment by lasashq** [comment]
❯ gcc --version

gcc (GCC) 14.2.1 20240910
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

❯ cargo install tgt --version

error: a value is required for '--version <VERSION>' but none was supplied

For more information, try '--help'.

**Comment by FedericoBruzzone** [comment]
Sorry, I meant `cargo install tgt --verbose`

**Comment by lasashq** [comment]
```
= note: /usr/bin/ld: warning: libc++.so.1, needed by /tmp/cargo-installHcCCi5/release/build/tdlib-rs-305b4f712dd03410/out/tdlib/lib/libtdjson.so, not found (try using -rpath or -rpath-link)
          /usr/bin/ld: warning: libunwind.so.1, needed by /tmp/cargo-installHcCCi5/release/build/tdlib-rs-305b4f712dd03410/out/tdlib/lib/libtdjson.so, not found (try using -rpath or -rpath-link)
          /usr/bin/ld: warning: libc++abi.so.1, needed by /tmp/cargo-installHcCCi5/release/build/tdlib-rs-305b4f712dd03410/out/tdlib/lib/libtdjson.so, not found (try using -rpath or -rpath-link)
```
          
          and there are many other errors with type "undefined reference"

**Comment by lasashq** [comment]
I tried to install these libraries which are rewuired by the installer, but there is another one error:

error: failed to run custom build command for `tdlib-rs v1.0.5`

```
Caused by:
  process didn't exit successfully: `/tmp/cargo-installdn48hM/release/build/tdlib-rs-7feee9859c0a132a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /home/antoine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tdlib-rs-1.0.5/build.rs:155:49:
  called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://github.com/FedericoBruzzone/tdlib-rs/releases/download/v1.0.5/tdlib-1.8.29-linux-x86_64.zip", source: TimedOut }
```

**Comment by lasashq** [comment]
if I try to build from source, next error occures:

```
error: failed to run custom build command for `tgt v1.0.0 (/home/antoine/tgt)`

Caused by:
  process didn't exit successfully: `/home/antoine/tgt/target/release/build/tgt-a7b37eb02ff74952/build-script-build` (exit status: 127)
  --- stderr
  /home/antoine/tgt/target/release/build/tgt-a7b37eb02ff74952/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
warning: build failed, waiting for other jobs to finish...
```

**Comment by EvgenyAfanasev** [comment]
You have to:
install libc++ from extra repo: https://archlinux.org/packages/extra/x86_64/libc++/
install libc++abi from extra repo: https://archlinux.org/packages/extra/x86_64/libc++abi/
install libunwind AND link `/usr/lib64/libunwind.so.1` to you version lib (in my case it is `/usr/lib64/libunwind.so.8.1.0`). I dont know why, but libunwind and lib and links without required tgt.

**Comment by FedericoBruzzone** [comment]
@lasashq  looks like you don't have installed `libc++` and `libc++abi`, retry the whole process after installing.
This is a common problem, more info at the issues #32  #39 and #62

@EvgenyAfanasev suggested correctly, thank you very much for the timely help!

**Comment by FedericoBruzzone** [comment]
@lasashq  Please, let us know if it works correctly :D

**Comment by lasashq** [comment]
Thank you! now everything is correct!
