### ISSUE TITLE
[feature]: add flake.nix to package project in Nix

### ISSUE THREAD

**Issue by zDonik1** [FedericoBruzzone/tgt#76]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a `flake.nix` added to the project so that `tgt` can be added as a Nix package in Nix systems.

**Describe the solution you'd like**
A `flake.nix` file added to the project root.

**Describe alternatives you've considered**
There are no alternatives other than compiling the project for the current system.

**Additional context**
I have already tried packaging the project into Nix, but the main hurdle is with copying the config files to `$HOME/.tgt/conifg` since Nix doesn't allow changing other directories except for a few allowed ones such as current source dir and installation dir.

AFAICT the only solution is to make the `tgt` app itself generate these config files where ever necessary in case they are missing on launch.

**Comment by FedericoBruzzone** [comment]
Thank you very much for your contribution!
Since you opened a PR in draft I think it's best to talk about it there.
