### ISSUE TITLE
[bug]: error: failed to run custom build command for `tgt v1.0.0`

### ISSUE THREAD

**Issue by alexlnkp** [FedericoBruzzone/tgt#87]
### Describe the bug

Trying to run `cargo install tgt` fails at the very end with the message in the title, followed by more messages. See "Logs and screenshots"

### Reproduction steps

1. Run `cargo install tgt`

### Expected behavior

No build errors expected.

### Logs and screenshots

```
error: failed to run custom build command for `tgt v1.0.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installROAmMd/release/build/tgt-473406629e3da5a3/build-script-build` (exit status: 127)
  --- stderr
  /tmp/cargo-installROAmMd/release/build/tgt-473406629e3da5a3/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tgt v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installROAmMd`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
Verbose logs:
```
. . .
   Compiling tgt v1.0.0
     Running `/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name build_script_build --edition=2021 /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tgt-1.0.0/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=158 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="download-tdlib"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("default", "download-tdlib", "local-tdlib", "pkg-config"))' -C metadata=473406629e3da5a3 -C extra-filename=-473406629e3da5a3 --out-dir /tmp/cargo-installH9Nr2i/release/build/tgt-473406629e3da5a3 -C strip=debuginfo -L dependency=/tmp/cargo-installH9Nr2i/release/deps --extern dirs=/tmp/cargo-installH9Nr2i/release/deps/libdirs-952d2040da74ad65.rlib --extern reqwest=/tmp/cargo-installH9Nr2i/release/deps/libreqwest-78b64e030eaa560b.rlib --extern tdlib_rs=/tmp/cargo-installH9Nr2i/release/deps/libtdlib_rs-0780b2c05f827906.rlib --extern zip=/tmp/cargo-installH9Nr2i/release/deps/libzip-fcee4c5d35bfb5c7.rlib --cap-lints allow -L native=/tmp/cargo-installH9Nr2i/release/build/tdlib-rs-53c6b41e2b2aeb94/out/tdlib/lib -L native=/usr/lib -L native=/tmp/cargo-installH9Nr2i/release/build/zstd-sys-ba94a246338f4659/out`
     Running `/tmp/cargo-installH9Nr2i/release/build/tgt-473406629e3da5a3/build-script-build`
error: failed to run custom build command for `tgt v1.0.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installH9Nr2i/release/build/tgt-473406629e3da5a3/build-script-build` (exit status: 127)
  --- stderr
  /tmp/cargo-installH9Nr2i/release/build/tgt-473406629e3da5a3/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tgt v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installH9Nr2i`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Trying to build from source by using `cargo build --release --features download-tdlib` in the cloned repo leads to the exact same error:
```
error: failed to run custom build command for `tgt v1.0.0 (/home/alex/Desktop/tgt)`

Caused by:
  process didn't exit successfully: `/home/alex/Desktop/tgt/target/release/build/tgt-cd939892f039d100/build-script-build` (exit status: 127)
  --- stderr
  /home/alex/Desktop/tgt/target/release/build/tgt-cd939892f039d100/build-script-build: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory
warning: build failed, waiting for other jobs to finish...
```

I am, however, using `rustup` as rustc and cargo provider, as oppose to using a package manager or an AUR. I'm not sure if that might've been the cause for the errors.

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

(Arch) Linux 6.11.6-arch1-1 x86_64 GNU/Linux

### Terminal and Command Line Interface (CLI) (including versions)

kitty 0.37.0 created by Kovid Goyal

### rustc and rustup target (including versions)

rustc 1.81.0 (eeb90cda1 2024-09-04) x86_64-unknown-linux-gnu

**Comment by FedericoBruzzone** [comment]
Thanks for reporting this issue.

Issue #32 should fix it, for both installation via Cargo and building from source.

Let me know :D

**Comment by alexlnkp** [comment]
> Thanks for reporting this issue.
> 
> Issue #32 should fix it, for both installation via Cargo and building from source.
> 
> Let me know :D

Oh! That worked!
I'm shocked I didn't notice that issue before and I'm honestly quite embarrassed by that.

I'm curious, however. Why does build look specifically for the `*.1` of the SO file? Why not just grab the regular SO without any of the version numbers in the name?
I'm admittedly not too knowledgeable in the topic of why SOs are even stored this way (with multiple symlinks pointing to the same SO, but with version numbers in the name), but wouldn't that be a solution to this problem as a whole?

**Comment by FedericoBruzzone** [comment]
No worries man! :D

I will try to answer your doubts.

- Shared libraries are often versioned so that programs needing a specific version can be dynamically linked with it directly.

- When libraries are installed, they often create symlinks. This approach provides a simple fallback mechanism where different versions of the library can coexist, and the program can use a compatible version without needing to be recompiled.

- Libraries are typically structured as:
  - libname.so → libname.so.1 → libname.so.1.0.0
  - The libname.so is a generic symlink, often used by developers at compile time.
  - libname.so.1 represents a stable API version, while libname.so.1.0.0 is a specific release.
This setup lets developers update the actual library (libname.so.1.0.1 for example) without breaking links for programs compiled with libname.so.1.

**Comment by alexlnkp** [comment]
> No worries man! :D
> 
> I will try to answer your doubts.
> 
>     * Shared libraries are often versioned so that programs needing a specific version can be dynamically linked with it directly.
> 
>     * When libraries are installed, they often create symlinks. This approach provides a simple fallback mechanism where different versions of the library can coexist, and the program can use a compatible version without needing to be recompiled.
> 
>     * Libraries are typically structured as:
>       
>       * libname.so → libname.so.1 → libname.so.1.0.0
>       * The libname.so is a generic symlink, often used by developers at compile time.
>       * libname.so.1 represents a stable API version, while libname.so.1.0.0 is a specific release.
>         This setup lets developers update the actual library (libname.so.1.0.1 for example) without breaking links for programs compiled with libname.so.1.

I see! Thanks for helping with understanding this, You are very kind :)
Closing this now!
