### ISSUE TITLE
[bug]: API_ID_PUBLISHED_FLOOD when trying to log in

### ISSUE THREAD

**Issue by ralencode** [FedericoBruzzone/tgt#95]
### Describe the bug

i installed tgt on archlinux with `cargo install tgt`. i had to install some libraries, `paru -S libc++abi libc++ llvm-libunwind`. then i checked if the binary is installed with `tgt -V` and `tgt-h` - everything is ok. next i run `tgt` and try to input my number: +79999999999, 79999999999, 89999999999 - nothing works, all i get is `API_ID_PUBLISHED_FLOOD` and it asks for number again

### Reproduction steps

1. archlinux
2. install cargo and build dependencies for tgt
3. cargo install tgt
4. tgt
5. input your phone number
6. no login

### Expected behavior

the app accepts my phone number and i proceed

### Logs and screenshots

![image](https://github.com/user-attachments/assets/1b531ee1-0448-4fee-8a5c-637cd6165b34)

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

Archlinux amd64

### Terminal and Command Line Interface (CLI) (including versions)

alacritty

### rustc and rustup target (including versions)

rustc 1.81.0 (eeb90cda1 2024-09-04) x86_64-unknown-linux-gnu

**Comment by Andreal2000** [comment]
Hi,
Have you checked if this other issue fix your problem ?

https://github.com/FedericoBruzzone/tgt/issues/63

**Comment by ralencode** [comment]
why should i generate my api key, and not the application? users should not bother with that, i think. but i will try, tho the description there is not that clear and i'll try to figure out how to generate my api key myself ig

**Comment by ralencode** [comment]
can i really just go and get my own api key?
![image](https://github.com/user-attachments/assets/bd3790df-4ed3-4dab-9b0b-8fd36c04820a)

**Comment by Andreal2000** [comment]
> why should i generate my api key, and not the application? users should not bother with that, i think.

We can't generate an api key for each user, as you can see the process cannot be automatized.
Currently we use the default api key of Telegram, but this problem can happen even if we ship tgt with our custom api key.

> but i will try, tho the description there is not that clear and i'll try to figure out how to generate my api key myself ig

If you read the last message of my colleague in the linked issue you can find the instruction to get you api key.
If that isn't clear enough you can follow this [link](https://core.telegram.org/api/obtaining_api_id) for a step by step guide.

> can i really just go and get my own api key?

Yes, you can go to Telegram website and get your api key.
For the error in the screenshot i suggest you to retry (maybe don't use url you don't own).
If the problem persist i suggest you to contact the Telegram support.

**Comment by ralencode** [comment]
i don't own any url, i just want to use this telegram client, i don't want to create my own telegram client or something. maybe there is a way to implement signing in with qr code or extract api keys from telegram desktop?

**Comment by Andreal2000** [comment]
This issue happen only to some user, maybe if you retry sign in without changing the api key it could work.

> i don't own any url, i just want to use this telegram client, i don't want to create my own telegram client or something.

Try get a key without inserting a url, if it's required use the url to your GitHub profile.

> maybe there is a way to implement signing in with qr code or extract api keys from telegram desktop?

The api key is for client not for user.
The api key is used to identify the client.
Even with the QR sign in the api key wouldn't change.
You can't extract the api key of Telegram Desktop because its generated by their developers and embedded in the app.

**Comment by rutexd** [comment]
Creating own appid and token has worked.

**Comment by Andreal2000** [comment]
Hi @rutexd, thanks for your feedback.
When @ralencode your problem will be fixed feels free to close this issue.

**Comment by ralencode** [comment]
i dont want to create appid myself, i want "just works", as nchat does
